### ISSUE TITLE
Efficient ground state computation methodologies for large molecules

### ISSUE THREAD

**Issue by AbdullahKazi500** [XanaduAI/QHack2023#33]
Project Name: Efficient ground state computation methodologies for large molecules

Team Name : Feynman Prodigies (Rank#15 Coding challenges)

Which challenges would you like to submit your project for?
TBD
(Quantum chemistry challenge)
(Hybrid Quantum classical computing challenge
Quantum computing today!
QEC and Compilation Challenge
NVIDIA Challenge
Amazon Braket Challenge)

**Project Description:** Finding the ground state of large molecules is a core problem in quantum chemistry and physics. In this project, we will compare the performance of different methodologies for finding the ground state of the molecule BeH2. We will use circuit cutting and knitting technique, to implement an algorithm which uses classical methods to augment the computation. This will involve an encoding and feedback during, before, and after training.  We will implement small scale error correction on qubits with highest error rates to control the quantum volume but at the same time get better results. We Will tackle the barren plateau problems through Adapt VQE Qiskit  Reference Paper : https://arxiv.org/pdf/2204.07179.pdf.
For error mitigation we will use the Qiskit Runtime Estimator primitive, with twirled readout error extinction, zero-noise extrapolation, or probabilistic error cancellation. Our sub-volume error correction protocol will involve a bit-flip error correction encoding. 

 Power-Up plan:
 **NVIDIA/Cyxtera/Run:AI Power-Ups**: In order to speed up the convergence of our algorithm, we need access to NVIDIA QODA which can give 287X speedup in end-to-end VQE performance https://developer.nvidia.com/qoda. We need more NVIDIA QPU's to parallelize the computation of independent parts tests to have comparison results quicker for the different methodologies in our project description.
**IBM Quantum & PINQ² Power-Ups**: Access to larger qubit IBM system will enable better QPU testing of large ansatze on how they converge to a ground state while employing the roto solve algorithm (https://pennylane.ai/qml/demos/tutorial_rotoselect.html) to converge faster to the ground state with an appropriate initial state. Additionally more shots and priority access to IBM QPU's will enable quicker testing of our algorithm.
**Amazon Braket Hackathon Power-Ups**: We need access to AWS QPU's and QPU's that work efficiently with hybrid algorithms. In particular Rigetti for our hybrid algorithm and D-Wave for an annealing approach to determining the ground state.

Project Link:  
link to our repository
 (https://github.com/jsaroni/QHack2023_Feynmanprodigies/commit/4389f575c5214eed3271031c2304705757ec2344)

 Access to power ups: 
(We have filled the Powerup form )
 "Yes".

We allow Xanadu Quantum Technologies to share our email addresses with the Power-Up Sponsors for the purpose of facilitating the delivery of the Power-Ups.
Yes 

(If applying for AWS’s credits) We have an AWS account

.
Yes 

(If applying for IBM’s dedicated slots) We confirm that We have filled in the form with the preferred slots.

Yes 

(If applying for IBM’s dedicated slots) We have obtained an IBM ID

Yes

**Comment by KetpuntoG** [comment]
Hey! Don't forget to put the link pointing to the commit instead of the main branch as shown in the readme video of this repo

**Comment by alvaro-at-xanadu** [comment]
Please don't forget to link to the latest commit instead of the main branch, as shown in the video in the ReadMe of this repo.

**Comment by jsaroni** [comment]
We linked the latest commit now.
